###
### Logstash with X-Pack
###

version: "3.3"

services:
  logstash:
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch.local:9200
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=elastic
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=P@ssw0rd.

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - SERVER_CRT_HOST=elasticsearch.local
      - SIMPLE_CA_URL=https://simple-ca.local
      - XPACK_EDITION=platinum
      - XPACK_BOOTSTRAP_PASSWORD=P@ssw0rd.
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=true
    networks:
      default:
        aliases:
          - elasticsearch.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
