###
### Logstash 2.x
###

version: "3.3"

services:
  logstash:
    command:
      --allow-env
      -w 2
      -e
        'input {
          http {
            port  => 5000
            type  => "test"
            ssl => true
            keystore => "config/keystore.jks"
            keystore_password => "$${JAVA_KEYSTORE_PWD}"
            verify_mode => "none"
          }
          heartbeat {
            interval => 10
            type => "heartbeat"
          }
        }
        output {
          stdout {
            codec => rubydebug { metadata => true }
          }
          if [type] == "test" {
            file {
              path => "data/events.json"
              codec => "json"
            }
          }
        }'
