###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  logstash:
    image: ${DOCKER_IMAGE}
    command: -f pipeline -w 2
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - LS_HEAP_SIZE=512m
    expose:
      # Logstash TCP input
      - 5000/tcp
    networks:
      default:
        aliases:
          - logstash.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - logstash
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=logstash.local:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - logstash
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=logstash.local:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  test_project_dir:
