###
### Logstash
###

version: "3.3"

networks:
  default:

services:
  logstash:
    image: ${DOCKER_IMAGE}
    depends_on:
      - simple_ca
    command:
      --pipeline.workers 2
      --config.string
        'input {
          http {
            port  => 5000
            type  => "test"
            ssl => true
            keystore => "config/keystore.jks"
            keystore_password => "$${JAVA_KEYSTORE_PWD}"
            verify_mode => "none"
          }
          heartbeat {
            interval => 10
            type => "heartbeat"
          }
        }
        output {
          stdout {
            codec => rubydebug { metadata => true }
          }
          if [type] == "test" {
            file {
              path => "data/events.json"
              codec => "json"
            }
          }
        }'
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - JAVA_TRUSTSTORE_PWD_FILE=/usr/share/logstash/config/truststore.pwd
      - JAVA_KEYSTORE_PWD_FILE=/usr/share/logstash/config/keystore.pwd
      - LS_HEAP_SIZE=512m
      - SERVER_CRT_HOST=${SERVER_CRT_HOST}
      - SERVER_KEY_PWD_FILE=/usr/share/logstash/config/server.pwd
      - SIMPLE_CA_URL=https://simple-ca.local
    expose:
      - 5000/tcp
    networks:
      default:
        aliases:
          - logstash.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - logstash
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=logstash.local:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - logstash
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=logstash.local:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  simple_ca_data:
  simple_ca_secrets:
  test_project_dir:
