version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: sicz/logstash:2.4.1
          working_directory: 2.4.1
          command: |
            make ci
      - run:
          name: sicz/logstash:5.6.2
          working_directory: 5.6.2
          command: |
            make ci
      - run:
          name: sicz/logstash:5.6.2-x-pack
          working_directory: 5.6.2/x-pack
          command: |
            make ci
      - run:
          name: sicz/logstash:6.0.0
          working_directory: 6.0.0
          command: |
            make ci
      - run:
          name: sicz/logstash:6.0.0-x-pack
          working_directory: 6.0.0/x-pack
          command: |
            make ci
      - deploy:
          name: Push images to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
