### DOCKER_IMAGE ###############################################################

LOGSTASH_VERSION	?= 5.6.0

DOCKER_IMAGE_TAGS	?= 5.6 5 latest

### MK_DOCKER_IMAGE ############################################################

PROJECT_DIR		?= $(abspath ..)
include $(PROJECT_DIR)/docker.version.mk

################################################################################
